export const COLLECTIONS = {
  ARTICULOS:          'articulos',
  PROVEEDORES:        'proveedores',
  CLIENTES:           'clientes',
  PRODUCTOS:          'productos',
  PRODUCTO_ARTICULOS: 'productoArticulos',
  COMPRAS:            'compras',
  COMPRA_ITEMS:       'compraItems',
  VENTAS:             'ventas',
  VENTA_ITEMS:        'ventaItems',
  USUARIOS:           'usuarios',
  PRESUPUESTOS:       'presupuestos',
  PRESUPUESTO_ITEMS:  'presupuestoItems',
  ORDENES:            'ordenes',
  ORDEN_ITEMS:        'ordenItems',
  RECIBOS:            'recibos',
  EMPRESAS:           'empresas',
  COMPROBANTES:       'comprobantes',
  COMPROBANTE_ITEMS:  'comprobanteItems',
} as const
